awe:
  #Do not change
  version: 21
  rendering:
    #amount of time (in ticks) the server will place a chunk of blocks
    interval: 1
    #how often that a user will get an update on the current que (number of intervals)
    talk-interval: 10
    #number of seconds before repeating a message
    talk-cooldown: 5
    #maximum size of the blocks queue
    queue-max-size-hard: 10000000
    #maximum number of blocks on the global queue before unlocing it
    queue-max-size-soft: 5000000
  memory:
    #minumum free memory (in kilobytes)
    #When the server memory runs below this value all operations are going to cancel
    #Use -1 for no limit
    minimumHard: 400000
    #the minimum free memory (In kulobytes) required to allow
    #block queuing after the hard limit is reached (soft > hard)
    minimumSoft: 600000
    #Force GC to run each X miliseconds (-1 - disable) when memory is low
    #Warning: if this is not handled correctly it can lead to TPS drop and timeouts!
    gcTimeout: 10000
  dispatcher:
    #maximum number of jobs performed in one run
    max-jobs: 2000
    #maximum number of idle runs before disabling the dispatcher
    max-idle-runs: 200
    #maximum number of miliseconds the dispatcher can use
    #This value should be lower than 50% of 1 tick (25ms)
    max-time: 20
  #Maximum number of blocks in que mode before AWE forces block placing.
  #Use -1 to disable force flush.
  forceFlushBlocks: 10000
  #Check for updates
  checkVersion: true
  #Disable or enable blocks physics freeze when placing blocks
  physicsFreez: true
  #File containing all the messages
  strings: "english.yml"
  messages:
    #Show debug messages
    debug: false
    #Show undo cleanup messages
    #Valid options: 
    # * off - no message (only errors),
    # * statup - show the message only on statrup
    # * [Default] on - show all undo cleanup messages
    undoCleanup: on
  #Disable async mode for
  overrides:
    #WorldEdit api calls
    disableForWeApi: false
    #for console player
    disableForConsole: false
    #for unknown player
    disableForUnknown: false
  #Blocks hub plugin options  
  blocksHub:
    log:
        #Enable block chang loggin
        isEnabled: true
        #Enable block change loggin for Direct Chunk API
        isDcEnabled: false
    #The block access control
    access:
        #Enable blocks access control
        isEnabled: false
        #Enable blocks access control for Direct Chunk API
        isDcEnabled: false
        #Allow NULL player to place blocks (used by some plugins)
        allowNull: false
        #Allow unknown player to place blocks
        allowUnknown: true
        #Allow console player to place blocks
        allowConsole: true
        #Allow offline player to place blocks
        allowOffline: false
  undo:
    #What to do with the undo data when server is running low on memory and 
    #the operation is running on the main thread
    #Allowed values: 
    # * off - memory is not checked while storing undo data (can lead to server crash)
    # * drop - do not store the undo data
    # * cancel - cancel current operation (throws max block changed)    
    memoryLowMain: cancel
    #What to do with the undo data when server is running low on memory and 
    #the operation is not running on the main thread
    #Allowed values: 
    # * off - memory is not checked while storing undo data (can lead to server crash)
    # * drop - do not store the undo data
    # * cancel - cancel current operation (throws max block changed)    
    # * wait - wait for GC to free up some memory
    memoryLow: wait
    #What to do with the undo data when server is running low on memory and 
    #the operation is not running on the main thread
    #Allowed values: 
    # * off - memory is not checked while storing undo data (can lead to server crash)
    # * drop - do not store the undo data
    # * wait - wait for GC to free up some memory
    memoryLowStorage: wait
    #Store the undo data on disk (a bit slower but does not use so much RAM)
    storeOnDisk: true
    #How much time should the WorldEdit session be kept after player logged out
    #Values: -1 Do not remove, 0 - immediately, X - Number of minutes
    keepSessionOnLogoutFor: 0
    #How long should the undo files be keept on the disk after the undo is no 
    #logner used in WE.
    #Values: -1 Do not delete, 0 - Delete immediately, X - Number of minutes to store 
    #the file
    keepUndoFileFor: 0
    #The number of minutes between undo files cleanup
    undoFileCleanupInterval: 30
  #The direct chunk options
  directChunk:
    #Do auto relight after each edit    
    autoRelight: true
    #New chunk light level (0-15)
    newSectionLightLevel: 0
    #Placed block light level (0-15), -1 for auto
    blockLightLevel: -1
  #Permissions options
  permissions:
    #If you are OP you will have all AWE permissions
    #Warning this causes the negative permissions to not work.
    opHasAll: true
    #Disable the global queue bypass, the player queue bypass works like before
    #If you do not want to run out of memory you hsould not set
    #the disableQueueBypass to false and opHasAll to true
    disableQueueBypass: true
  #Player permission groups.
  #Permission node: AWE.Groups.<group name>  
  permissionGroups:
    #The group entry (at least one group is required!)
    #If a player has multiple groups, the last one defined in the config
    #is assigned. (Lower the group the lower the 'weight' if you can compare it to PEX)
    default:
      #Indicates that the group is called default.
      #Only one group can be default, if multiple groups are set to default
      #the first one is used as default. The default group is used for players
      #that do not have any other permission groups assigned to them.
      isDefault: true
      #Maximum number of jobs a player can have. -1 = no job limit
      maxJobs: 1
      #Enable or disable auto job cancelation on player quit
      cleanOnLogout: true
      #Default AWE status for loging in players 
      defaultMode: on
      #Disable the WorldEdit undo
      disableUndo: false
      renderer:
        #blocks to place (per-interval), this determines the max speed of block placing
        #if you experience lag lower this and the next number (time), use -1 for no limit
        blocks: 10000
        #Maximum number of miliseconds spend on placing blocks, use -1 for no limit
        time: 75
      queue:
        #maximum size of the player block queue
        limit-hard: 500000
        #number of blocks on the player queue when to stop placing blocks
        limit-soft: 250000
      messages:
        #Whether or not to show progress using BarAPI
        progress-bar: true
        #minimum number of blocks to display the progress bar
        progress-bar-min: 100
        #Whether or not to show progress using the chat messages
        progress-chat: true
        #is async world edit talkative 
        talkative: true
      #The WorldEdit config override
      worldedit:
        #Maximum number of undoos
        historySize: 15
        #Maximum number of changed blocks
        maxBlockChanged: -1
        #List of dissallowed block ID
        disallowedBlocks: [6, 7, 14, 15, 16, 26, 27, 28, 29, 39, 31, 32, 33, 34, 36, 37, 38, 39, 40, 46, 50, 51, 56, 59, 69, 73, 74, 75, 76, 77, 81, 83]
        #The dissallowed black list handling
        disallowedBlocksUsage:
          #Use black list in patterns
          patterns: true
          #Block set (every block set operation)
          blockSet: false
    #Example of additional vip group:
    #vip:
    #  #you can remove this, the isDefault is by default set to false
    #  isDefault: false 
    #  maxJobs: -1
    #    cleanOnLogout: false
    #  #You can omit entries with that are same value as in the default group
    #  #defaultMode: on
    #  #Disable the WorldEdit undo
    #  disableUndo: true
    #  renderer:
    #    blocks: 20000
    #    time: -1
  #List of WorldEdit operations that AWE won't run in async mode
  disabledOperations: {}
  #  - undo
  #  - redo
  #  - fillXZ
  #  - fillXY
  #  - fillZY
  #  - fill3d
  #  - removeAbove
  #  - removeBelow
  #  - removeNear
  #  - setBlocks
  #  - replaceBlocks
  #  - makeCuboidFaces
  #  - makeCuboidWalls
  #  - overlayCuboidBlocks
  #  - naturalizeCuboidBlocks
  #  - stackCuboidRegion
  #  - moveCuboidRegion
  #  - drainArea
  #  - fixLiquid
  #  - makeCylinder
  #  - makeSphere
  #  - makePyramid
  #  - thaw
  #  - simulateSnow
  #  - green
  #  - makePumpkinPatches
  #  - makeForest
  #  - makeShape
  #  - deformRegion
  #  - hollowOutRegion
  #  - paste
  #  - copy
  #  - cut
  #  - regenerate
  #  - center
  #  - drawLine
  #  - drawSpline
  #  - makeBiomeShape
  #  - forest
  #  - flora
  #  - setBiome
  #  - loadSchematic
  #  - saveSchematic
  #  - craftScript
  #  - makeFaces
  #  - makeWalls
  #  - overlayBlocks
  #  - naturalizeBlocks
  #  - stackRegion
  #  - moveRegion
  #  - schematicInfo
  #  - placeSchematic
  #  - chunkSet
  #  - chunkClear
  #  - chunkFill
  #  - chunkClone
  #  - chunkPaste
  #  - chunkCopy
  #  - chunkRelight
  #  - brush
  #  - smooth
  #  - tool
  #  - tree
  #  - pickaxe
